// Auto-generated by buildGenerated.ts — do not edit by hand
import type { Challenge } from '../challengeTypes.js'

export const generatedChallenges: Challenge[] = [
  {
    "id": "c-031",
    "title": "Något röd",
    "description": "Hämta det mest röda föremålet du kan hitta. Vid oavgjort vinner störst föremål. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-032",
    "title": "Röd jakt",
    "description": "Ta med dig tre olika röda saker. Testledaren bedömer vem som hade mest övertygande röd samling.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-033",
    "title": "Något blå",
    "description": "Hämta det mest blåa föremålet du kan hitta. Vid oavgjort vinner störst föremål. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-034",
    "title": "Blå jakt",
    "description": "Ta med dig tre olika blåa saker. Testledaren bedömer vem som hade mest övertygande blå samling.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-035",
    "title": "Något grön",
    "description": "Hämta det mest gröna föremålet du kan hitta. Vid oavgjort vinner störst föremål. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-036",
    "title": "Grön jakt",
    "description": "Ta med dig tre olika gröna saker. Testledaren bedömer vem som hade mest övertygande grön samling.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-037",
    "title": "Något gul",
    "description": "Hämta det mest gula föremålet du kan hitta. Vid oavgjort vinner störst föremål. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-038",
    "title": "Gul jakt",
    "description": "Ta med dig tre olika gula saker. Testledaren bedömer vem som hade mest övertygande gul samling.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-039",
    "title": "Något lila",
    "description": "Hämta det mest lilaa föremålet du kan hitta. Vid oavgjort vinner störst föremål. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-040",
    "title": "Lila jakt",
    "description": "Ta med dig tre olika lilaa saker. Testledaren bedömer vem som hade mest övertygande lila samling.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-041",
    "title": "Något orange",
    "description": "Hämta det mest orangea föremålet du kan hitta. Vid oavgjort vinner störst föremål. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-042",
    "title": "Orange jakt",
    "description": "Ta med dig tre olika orangea saker. Testledaren bedömer vem som hade mest övertygande orange samling.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-043",
    "title": "Något rosa",
    "description": "Hämta det mest rosaa föremålet du kan hitta. Vid oavgjort vinner störst föremål. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-044",
    "title": "Rosa jakt",
    "description": "Ta med dig tre olika rosaa saker. Testledaren bedömer vem som hade mest övertygande rosa samling.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-045",
    "title": "Något svart",
    "description": "Hämta det mest svarta föremålet du kan hitta. Vid oavgjort vinner störst föremål. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-046",
    "title": "Svart jakt",
    "description": "Ta med dig tre olika svarta saker. Testledaren bedömer vem som hade mest övertygande svart samling.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-047",
    "title": "Något vit",
    "description": "Hämta det mest vita föremålet du kan hitta. Vid oavgjort vinner störst föremål. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-048",
    "title": "Vit jakt",
    "description": "Ta med dig tre olika vita saker. Testledaren bedömer vem som hade mest övertygande vit samling.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-049",
    "title": "Något brun",
    "description": "Hämta det mest bruna föremålet du kan hitta. Vid oavgjort vinner störst föremål. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-050",
    "title": "Brun jakt",
    "description": "Ta med dig tre olika bruna saker. Testledaren bedömer vem som hade mest övertygande brun samling.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-051",
    "title": "Något turkos",
    "description": "Hämta det mest turkosa föremålet du kan hitta. Vid oavgjort vinner störst föremål. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-052",
    "title": "Turkos jakt",
    "description": "Ta med dig tre olika turkosa saker. Testledaren bedömer vem som hade mest övertygande turkos samling.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-053",
    "title": "Något silver",
    "description": "Hämta det mest silvera föremålet du kan hitta. Vid oavgjort vinner störst föremål. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-054",
    "title": "Silver jakt",
    "description": "Ta med dig tre olika silvera saker. Testledaren bedömer vem som hade mest övertygande silver samling.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-055",
    "title": "Något rund",
    "description": "Hämta något rund. Det rundaste föremålet du kan hitta vinner. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-056",
    "title": "Något tung",
    "description": "Hämta något tung. Det tyngsta föremålet du kan bära tillbaka till testledaren vinner. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-057",
    "title": "Något mjuk",
    "description": "Hämta något mjuk. Det mjukaste föremålet vinner. Testledaren får klämma. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-058",
    "title": "Något gammalt",
    "description": "Hämta något gammalt. Det äldsta föremålet med tydlig ålder vinner — motivera muntligt. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-059",
    "title": "Något konstigt",
    "description": "Hämta något konstigt. Det konstigaste föremålet i hemmet vinner. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-060",
    "title": "Något dyrt",
    "description": "Hämta något dyrt. Det som ser dyrast ut vinner. Priset spelar ingen roll. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-061",
    "title": "Något billigt",
    "description": "Hämta något billigt. Det billigaste föremålet du hittar vinner. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-062",
    "title": "Något stort",
    "description": "Hämta något stort. Det största föremålet du kan bära ensam vinner. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-063",
    "title": "Något litet",
    "description": "Hämta något litet. Det minsta föremålet som syns med blotta ögat vinner. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-064",
    "title": "Något blankt",
    "description": "Hämta något blankt. Det blankaste/speglande föremålet vinner. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-065",
    "title": "Något ljudligt",
    "description": "Hämta något ljudligt. Det föremål som gör bäst ljud när testledaren testar det vinner. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-066",
    "title": "Något doftande",
    "description": "Hämta något doftande. Det doftande föremålet med bäst (eller värst) doft vinner. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-067",
    "title": "Något klibbigt",
    "description": "Hämta något klibbigt. Det klibbigaste föremålet du vågar ta med vinner. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-068",
    "title": "Något skarpt",
    "description": "Hämta något skarpt. Det vassaste föremålet du hittar vinner — var försiktig! Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-069",
    "title": "Något varmt",
    "description": "Hämta något varmt. Det varmaste föremålet just nu vinner. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-070",
    "title": "Självporträtt",
    "description": "Rita ett självporträtt utan att titta i spegel. Testledaren bedömer likheten. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-071",
    "title": "Drömhus",
    "description": "Rita ditt drömhus på tre sekunder — nej, du har mer tid, men håll det enkelt. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-072",
    "title": "Monster",
    "description": "Rita ett monster som bor under soffan. Mest skrämmande vinner. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-073",
    "title": "Superhjälte",
    "description": "Rita dig själv som superhjälte. Mest heroisk vinner. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-074",
    "title": "Katt-hund",
    "description": "Rita en katt som tror att den är en hund. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-075",
    "title": "Robot",
    "description": "Rita en robot som gör något vardagligt (t.ex. diskar). Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-076",
    "title": "Karta hem",
    "description": "Rita en karta från dörren till kylskåpet. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-077",
    "title": "Familjeträd",
    "description": "Rita ett familjeträd — figurer räcker, namn valfritt. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-078",
    "title": "Logo",
    "description": "Designa en logotyp för kvällens fest. Ett tecken räcker. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-079",
    "title": "Emblem",
    "description": "Rita ett emblem för din egen hederliga orden. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-080",
    "title": "Flagga",
    "description": "Designa en flagga för det här rummet. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-081",
    "title": "Tatuering",
    "description": "Rita en tatuering testledaren borde skaffa. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-082",
    "title": "Tatuering del 2",
    "description": "Rita samma tatuering på fel kroppsdel. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-083",
    "title": "Maträtt",
    "description": "Rita dagens middag som fine dining-upplägg. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-084",
    "title": "Alien",
    "description": "Rita en alien som precis landat i hallen. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-085",
    "title": "Dinosaurie",
    "description": "Rita en dinosaurie som klarar vuxenlivet. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-086",
    "title": "Banan 2.0",
    "description": "Rita en frukt som är för cool för att vara frukt. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-087",
    "title": "Husdjur",
    "description": "Rita ditt påhittade husdjur. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-088",
    "title": "Skor",
    "description": "Rita skor designade för att gå på lava. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-089",
    "title": "Hatt",
    "description": "Rita världens mest over-the-top hatt. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-090",
    "title": "Vinter",
    "description": "Rita en snögubbe i badshorts. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-091",
    "title": "Sommar",
    "description": "Rita en sol som är trött på sommaren. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-092",
    "title": "Musik",
    "description": "Rita hur din favoritlåt skulle se ut som form. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-093",
    "title": "Kaos",
    "description": "Rita kaos. Förklara inte. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-094",
    "title": "Ord",
    "description": "Rita ordet \"TOMTE\" utan att skriva bokstäver — bara bild. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-095",
    "title": "Pil",
    "description": "Rita en pil som pekar på testledarens nästa karriärsteg. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-096",
    "title": "Hjärna",
    "description": "Rita en hjärna som tänker på något pinsamt. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-097",
    "title": "Hand",
    "description": "Rita din hand utan att titta på den. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-098",
    "title": "Fot",
    "description": "Rita din fot med skon på — blundar du? Det får du välja. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-099",
    "title": "Rymden",
    "description": "Rita en planet där alla bara fikar. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-100",
    "title": "Bil",
    "description": "Rita en bil som passar testledarens personlighet. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-101",
    "title": "Båt",
    "description": "Rita en båt som seglar på te. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-102",
    "title": "Träd",
    "description": "Rita ett träd som har sett saker. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-103",
    "title": "Blomma",
    "description": "Rita en blomma som är sur på måndagar. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-104",
    "title": "Insekter",
    "description": "Rita tre insekter som diskuterar vädret. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-105",
    "title": "Stad",
    "description": "Rita en stad där alla hus är kuddar. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-106",
    "title": "Bro",
    "description": "Rita en bro mellan två möbler i rummet. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-107",
    "title": "Tåg",
    "description": "Rita ett tåg som är försenat av känslor. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-108",
    "title": "Flygplan",
    "description": "Rita ett flygplan som är rädd för höjder. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-109",
    "title": "Glass",
    "description": "Rita världens sorgligaste glass. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 180,
    "submissionMode": "draw"
  },
  {
    "id": "c-110",
    "title": "Haiku om ledaren",
    "description": "Skriv ett haiku om testledaren. Fem-sju-fem stavelser om du orkar. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-111",
    "title": "Fake tweet",
    "description": "Skriv en tweet från testledaren som skulle ställa till det. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-112",
    "title": "Rubrik",
    "description": "Skriv en tidningsrubrik om det som hände dig senaste dygnet. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-113",
    "title": "Recension 2",
    "description": "Ge kvällens snacks betyg 1–5 och motivera som en krass matkritiker. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-114",
    "title": "Reklam",
    "description": "Skriv en reklamtext för något oanvändbart i rummet. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-115",
    "title": "Sångtext",
    "description": "Skriv två rader sångtext om att vara i det här rummet. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-116",
    "title": "Rap",
    "description": "Skriv fyra rader rap om testledarens domarenergi. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-117",
    "title": "Horoskop",
    "description": "Skriv dagens horoskop för testledaren. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-118",
    "title": "Obituary",
    "description": "Skriv en överdrivet dramatisk nekrolog för en socka som försvann. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-119",
    "title": "Manual",
    "description": "Skriv en felaktig bruksanvisning för en stol. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-120",
    "title": "Varning",
    "description": "Skriv en varningsskylt för testledarens humör. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-121",
    "title": "Brev",
    "description": "Skriv ett kort brev till ditt framtida jag efter den här kvällen. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-122",
    "title": "Lista",
    "description": "Skriv en topplista: tre saker som borde vara olagliga i det här rummet. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-123",
    "title": "Regler",
    "description": "Skriv tre nya husregler för kvällen. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-124",
    "title": "Namn",
    "description": "Hitta på ett nytt ord för \"när någon tar sista biten utan att fråga\". Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-125",
    "title": "Definition",
    "description": "Skriv en falsk ordboksdefinition av \"testledare\". Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-126",
    "title": "Dialog",
    "description": "Skriv dialog mellan två möbler i rummet. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-127",
    "title": "Film",
    "description": "Skriv en logline till en skräckfilm som utspelar sig här. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-128",
    "title": "Podcast",
    "description": "Skriv intro till en true crime-podcast om försvunna fjärrkontroller. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-129",
    "title": "SMS",
    "description": "Skriv det mest pinsamma SMS du kan hitta på att skicka till fel person. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-130",
    "title": "Status",
    "description": "Skriv en Facebook-status från 2012 om den här kvällen. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-131",
    "title": "LinkedIn",
    "description": "Skriv en cringe LinkedIn-post om att \"vinna\" det här testet. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-132",
    "title": "Tinder",
    "description": "Skriv en Tinder-bio för testledaren baserat på ikväll. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-133",
    "title": "Yelp",
    "description": "Recensera testledarens domarskrik som om det vore en restaurang. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-134",
    "title": "Amazon",
    "description": "Skriv en femstjärnig recension av något helt meningslöst. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-135",
    "title": "Dröm",
    "description": "Beskriv en absurd dröm där alla här är med. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-136",
    "title": "Alibi",
    "description": "Skriv ditt alibi för var du var igår kl. 19:00. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-137",
    "title": "Konspiration",
    "description": "Skriv en konspirationsteori om varför testledaren har den kappen. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-138",
    "title": "Manifest",
    "description": "Skriv tre punkter i ett manifest för laget som förlorar. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-139",
    "title": "Tal",
    "description": "Skriv början på ett seger- eller förlusttal till laget. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-140",
    "title": "Barnbok",
    "description": "Skriv första meningen i en barnbok om en testledare. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-141",
    "title": "Slutet",
    "description": "Skriv slutet på en saga som började med \"Det var en gång en kudde\". Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-142",
    "title": "Rätt stavning",
    "description": "Stava testledarens namn på fem kreativa sätt. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-143",
    "title": "Acronym",
    "description": "Skapa en förkortning av ditt namn som låter som en myndighet. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-144",
    "title": "Slogan",
    "description": "Skriv en reklamslogan för att sälja tystnad i det här rummet. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-145",
    "title": "News anchor",
    "description": "Läs upp din senaste tanke högt som en nyhetsuppläsare. Bäst gravitas vinner.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-146",
    "title": "Opera",
    "description": "Sjung (eller nynna) en mening om testledaren operastil.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-147",
    "title": "Shakespeare",
    "description": "Framför en Shakespeare-monolog om att vara hungrig.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-148",
    "title": "Robotdans",
    "description": "Dansa som en robot tills testledaren säger stopp. Mest mekaniskt vinner.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-149",
    "title": "Staty",
    "description": "Stå som en staty. Den som rör sig minst efter stopp vinner.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-150",
    "title": "Tunga twister",
    "description": "Säg \"sju sjösjuka sjömän\" fem gånger snabbt. Flest klara utan att skratta vinner.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-151",
    "title": "Accent",
    "description": "Prata med en accent i 30 sekunder. Testledaren väljer bäst (och värst).",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-152",
    "title": "Whisper",
    "description": "Viska något dramatiskt till testledaren. Mest teatralt vinner.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-153",
    "title": "Rädd",
    "description": "Spela upp att du just såg ett spöke bakom testledaren.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-154",
    "title": "Reklamfilm",
    "description": "Gör en 15-sekunders reklam för vatten.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-155",
    "title": "Nature documentary",
    "description": "Kommentera testledaren som David Attenborough.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-156",
    "title": "Sport",
    "description": "Ge en sportkommentator-beskrivning av någon i rummet.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-157",
    "title": "Weather",
    "description": "Presentera vädret i det här rummet som en meteorolog.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-158",
    "title": "Auction",
    "description": "Ropa ut ett föremål i rummet på auktion. Högst bud vinner inget — bara poäng.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-159",
    "title": "Motivation",
    "description": "Ge testledaren en överdrivet peppig motivationsmonolog.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-160",
    "title": "Therapist",
    "description": "Ge testledaren tre sekunders terapi.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-161",
    "title": "Fortune teller",
    "description": "Spå testledarens framtid baserat på deras skor.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-162",
    "title": "Chef",
    "description": "Låtsas vara kock och presentera en imaginär rätt.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-163",
    "title": "Pilot",
    "description": "Gör säkerhetsinstruktioner för det här rummet.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-164",
    "title": "Tour guide",
    "description": "Guida oss genom rummet som om det vore ett museum.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-165",
    "title": "Villain",
    "description": "Presentera dig som skurk och förklara din plan.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-166",
    "title": "Hero entrance",
    "description": "Gör en hjältemodig entré in i bild.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-167",
    "title": "Slow motion",
    "description": "Gör något vardagligt i slow motion. Mest filmiskt vinner.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-168",
    "title": "Mime",
    "description": "Mima att du klättrar på en osynlig stege.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-169",
    "title": "Puppet",
    "description": "Låt din hand vara en marionett som introducerar dig.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-170",
    "title": "Evil laugh",
    "description": "Gör det bästa skurklig skrattet.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-171",
    "title": "Compliment battle",
    "description": "Ge testledaren den mest specifika komplimangen.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-172",
    "title": "Roast",
    "description": "Ge testledaren en mild roast som ändå känns ärlig.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-173",
    "title": "Pickup line",
    "description": "Använd en raggningsreplik på ett kaffekopp.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-174",
    "title": "Breakup",
    "description": "Gör slut med en stol på ett dramatiskt sätt.",
    "type": "subjective",
    "submissionMode": "physical"
  },
  {
    "id": "c-175",
    "title": "Handuppristräning",
    "description": "Håll händerna rakt upp i luften. Sista som står kvar vinner. Testledaren avslutar när det är klart.",
    "type": "endurance"
  },
  {
    "id": "c-176",
    "title": "Squat hold",
    "description": "Stå i squat. Sista person som håller vinner. Testledaren avslutar när det är klart.",
    "type": "endurance"
  },
  {
    "id": "c-177",
    "title": "Vägg-sits",
    "description": "Sitt mot väggen som om du hade en osynlig stol. Sista vinner. Testledaren avslutar när det är klart.",
    "type": "endurance"
  },
  {
    "id": "c-178",
    "title": "Armhävningar",
    "description": "Gör så många armhävningar (på knä räknas) tills testledaren avslutar. Testledaren avslutar när det är klart.",
    "type": "endurance"
  },
  {
    "id": "c-179",
    "title": "Hopp på ett ben",
    "description": "Hoppa på ett ben. Sista som hoppar vinner. Testledaren avslutar när det är klart.",
    "type": "endurance"
  },
  {
    "id": "c-180",
    "title": "Tung blick",
    "description": "Stirra på testledaren utan att blinka. Sista som blinkar förlorar — vinnare är kvar. Testledaren avslutar när det är klart.",
    "type": "endurance"
  },
  {
    "id": "c-181",
    "title": "Ingen skratt",
    "description": "Testledaren försöker få dig att skratta. Sista som håller sig allvarlig vinner. Testledaren avslutar när det är klart.",
    "type": "endurance"
  },
  {
    "id": "c-182",
    "title": "Bubble face",
    "description": "Blås kinderna och håll luften. Sista vinner. Testledaren avslutar när det är klart.",
    "type": "endurance"
  },
  {
    "id": "c-183",
    "title": "Tongue out",
    "description": "Stick ut tungan och håll. Sista vinner. Testledaren avslutar när det är klart.",
    "type": "endurance"
  },
  {
    "id": "c-184",
    "title": "Superman",
    "description": "Ligg som superman (armar och ben lyft). Sista vinner. Testledaren avslutar när det är klart.",
    "type": "endurance"
  },
  {
    "id": "c-185",
    "title": "Bok på huvudet",
    "description": "Balansera en bok på huvudet. Sista som tappar förlorar. Testledaren avslutar när det är klart.",
    "type": "endurance"
  },
  {
    "id": "c-186",
    "title": "Te-glas",
    "description": "Håll en mugg/teglas med utsträckt arm. Sista vinner. Testledaren avslutar när det är klart.",
    "type": "endurance"
  },
  {
    "id": "c-187",
    "title": "Kedja",
    "description": "Håll i någons axel och stå still. Kedjan får inte brytas. Testledaren avslutar när det är klart.",
    "type": "endurance"
  },
  {
    "id": "c-188",
    "title": "Högsta ljudet 2",
    "description": "Gör ett ljud och håll det. Längst vinner. Testledaren avslutar när det är klart.",
    "type": "endurance"
  },
  {
    "id": "c-189",
    "title": "Andning",
    "description": "Andas så tyst du kan medan testledaren lyssnar. Mest tyst vinner. Testledaren avslutar när det är klart.",
    "type": "endurance"
  },
  {
    "id": "c-190",
    "title": "Stå på tå",
    "description": "Stå på tå. Sista vinner. Testledaren avslutar när det är klart.",
    "type": "endurance"
  },
  {
    "id": "c-191",
    "title": "Knäböj",
    "description": "Håll knäböj. Sista vinner. Testledaren avslutar när det är klart.",
    "type": "endurance"
  },
  {
    "id": "c-192",
    "title": "Planka på knä",
    "description": "Planka på knä om full planka är för hårt. Sista vinner. Testledaren avslutar när det är klart.",
    "type": "endurance"
  },
  {
    "id": "c-193",
    "title": "Vända på huvudet",
    "description": "Stå upp och ned (huvudet nedåt mot möbel) så länge du orkar. Testledaren avslutar när det är klart.",
    "type": "endurance"
  },
  {
    "id": "c-194",
    "title": "Finger fight",
    "description": "Håll pekfingret upp utan att böja det. Sista vinner. Testledaren avslutar när det är klart.",
    "type": "endurance"
  },
  {
    "id": "c-195",
    "title": "Ingen ord",
    "description": "Du får inte prata. Sista som pratar förlorar. Testledaren avslutar när det är klart.",
    "type": "endurance"
  },
  {
    "id": "c-196",
    "title": "Leendets fång",
    "description": "Le utan att skratta. Sista som skrattar förlorar. Testledaren avslutar när det är klart.",
    "type": "endurance"
  },
  {
    "id": "c-197",
    "title": "Kramkudde",
    "description": "Krama en kudde hårt. Sista som släpper vinner. Testledaren avslutar när det är klart.",
    "type": "endurance"
  },
  {
    "id": "c-198",
    "title": "Iskall",
    "description": "Håll något kallt från kylen. Sista vinner. Testledaren avslutar när det är klart.",
    "type": "endurance"
  },
  {
    "id": "c-199",
    "title": "Vänta",
    "description": "Stå helt still i mitten av rummet. Sista som rör sig vinner. Testledaren avslutar när det är klart.",
    "type": "endurance"
  },
  {
    "id": "c-200",
    "title": "Hatt av det du har",
    "description": "Bygg en hatt av föremål du har på dig eller inom räckhåll. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-201",
    "title": "Krona",
    "description": "Bygg en krona värdig testledaren. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-202",
    "title": "Trofé",
    "description": "Bygg ett trofé för kvällens förlorare. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-203",
    "title": "Monument",
    "description": "Bygg ett monument över dagens första måltid. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-204",
    "title": "Bro",
    "description": "Bygg en bro mellan två ytor med saker i rummet. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-205",
    "title": "Bil",
    "description": "Bygg en \"bil\" du kan sitta i. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-206",
    "title": "Flygplan",
    "description": "Bygg något som ser flygplan-aktigt ut. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-207",
    "title": "Båt",
    "description": "Bygg en båt som flottar i badkaret — nej, den får stå på golvet. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-208",
    "title": "Robot",
    "description": "Bygg en robot av minst fem delar. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-209",
    "title": "Dinosaurie",
    "description": "Bygg en dinosaurie som hotar testledaren. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-210",
    "title": "Museum",
    "description": "Ställ ut tre föremål som ett mini-museum med etiketter (muntligt räcker). Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-211",
    "title": "Mode",
    "description": "Skapa en outfit av hushållspapper, filtar eller vad som finns. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-212",
    "title": "Skylt",
    "description": "Gör en protestskylt om något löjligt i rummet. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-213",
    "title": "Flagga fysisk",
    "description": "Bygg en fysisk flagga för ditt lag. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-214",
    "title": "Instrument",
    "description": "Bygg ett musikinstrument som faktiskt låter. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-215",
    "title": "Telefon",
    "description": "Bygg en \"telefon\" och ring testledaren. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-216",
    "title": "Kamera",
    "description": "Bygg en kamera och \"fota\" testledaren. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-217",
    "title": "Trädgård",
    "description": "Bygg en miniatyrträdgård på bordet. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-218",
    "title": "Stad",
    "description": "Bygg en stad i miniatyr. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-219",
    "title": "Landskap",
    "description": "Bygg ett landskap med minst tre höjdnivåer. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-220",
    "title": "Mat",
    "description": "Presentera en \"maträtt\" av minst tre ingredienser visuellt. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-221",
    "title": "Cocktail",
    "description": "Skapa en mocktail och presentera den som om du vore bartender. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-222",
    "title": "Present",
    "description": "Slå in en meningslös gåva till testledaren. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-223",
    "title": "Time capsule",
    "description": "Packa en tidskapsel av tre saker från rummet. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-224",
    "title": "Altare",
    "description": "Bygg ett mini-altare till testledaren. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-225",
    "title": "Tron",
    "description": "Bygg en tron av kuddar. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-226",
    "title": "Fängelse",
    "description": "Bygg ett fängelse för en mobiltelefon. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-227",
    "title": "Zoo",
    "description": "Bygg burar för tre \"djur\" (föremål). Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-228",
    "title": "Parad",
    "description": "Linje upp föremål i parad och presentera dem. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-229",
    "title": "Red carpet",
    "description": "Bygg en röda mattan-upplevelse med det du har. Testledaren bedömer när du är klar.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-230",
    "title": "Skosnöre",
    "description": "Knyt skosnörena snabbast. Båda skorna. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-231",
    "title": "Sängbäddning",
    "description": "Bädda om en säng eller soffa snyggast snabbast. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-232",
    "title": "Pappersflygplan",
    "description": "Vik ett pappersflygplan som flyger längst. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-233",
    "title": "Torn av kort",
    "description": "Bygg högst torn av spelkort eller papper. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-234",
    "title": "Balans",
    "description": "Balansera en sked på näsan längst. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-235",
    "title": "Kast",
    "description": "Kasta något mjukt i en korg/balja längst avstånd. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-236",
    "title": "Hopprep",
    "description": "Hoppa hopprep (inbillat räknas om rep saknas) flest gånger på 30 sek. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-237",
    "title": "Push-ups snabb",
    "description": "Flest armhävningar på tid — testledaren räknar. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-238",
    "title": "Jumping jacks",
    "description": "Flest jumping jacks på tid. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-239",
    "title": "High knees",
    "description": "Flest high knees på tid. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-240",
    "title": "Spin",
    "description": "Snurra runt och stå still utan att ramla. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-241",
    "title": "Limbo",
    "description": "Gå under något utan att röra det. Lägst vinner. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-242",
    "title": "Limbo 2",
    "description": "Håll en bok på huvudet och gå snabbast till dörren. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-243",
    "title": "Transfer",
    "description": "Flytta tre föremål från A till B snabbast. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-244",
    "title": "Sort",
    "description": "Sortera tio saker efter färg snabbast. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-245",
    "title": "Fold",
    "description": "Vik en filt eller handduk snyggast snabbast. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-246",
    "title": "Stack cups",
    "description": "Stapla flest muggar/koppar utan att de faller. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-247",
    "title": "Ping pong",
    "description": "Studsa en boll (eller servett) flest gånger. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-248",
    "title": "Keepy uppy",
    "description": "Håll en ballong/servett i luften längst. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-249",
    "title": "Crab walk",
    "description": "Gå som krabba snabbast tvärs rummet. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-250",
    "title": "Bear crawl",
    "description": "Björngång snabbast. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-251",
    "title": "Backwards",
    "description": "Gå baklänges snabbast till vald punkt. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-252",
    "title": "Whisper run",
    "description": "Spring tystast till dörren och tillbaka. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-253",
    "title": "Object relay",
    "description": "Tagga testledaren med ett föremål snabbast (försiktigt!). Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-254",
    "title": "Paper tear",
    "description": "Riv papper i en så lång remsa som möjligt. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-255",
    "title": "Origami",
    "description": "Vik en svan snabbast (ful får vara). Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-256",
    "title": "Knot",
    "description": "Knyt flest knutar på ett rep/snöre på tid. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-257",
    "title": "Coin flip",
    "description": "Flest lyckade myntkast i rad (mynt valfritt — låtsas räknas med heder). Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-258",
    "title": "Dice roll",
    "description": "Kasta tärning högst totalt på tre kast. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-259",
    "title": "Card house",
    "description": "Bygg högst korthus på kort tid. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-260",
    "title": "Byt plats",
    "description": "Byt plats med någon utan att prata. Snabbast och smidigast vinner.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-261",
    "title": "Mystery box",
    "description": "Hämta något från ett annat rum utan att säga vad. Testledaren gissar.",
    "type": "subjective",
    "timeLimitSeconds": 90,
    "submissionMode": "physical"
  },
  {
    "id": "c-262",
    "title": "Outfit swap",
    "description": "Byt en accessoar med någon. Bäst match vinner.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-263",
    "title": "Sock puppet",
    "description": "Gör en strumpdocka och introducera den.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-264",
    "title": "Fort",
    "description": "Bygg ett fort och försvara det med en mening.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-265",
    "title": "Campfire",
    "description": "Berätta en skräckhistoria om en lampa.",
    "type": "subjective",
    "timeLimitSeconds": 90,
    "submissionMode": "physical"
  },
  {
    "id": "c-266",
    "title": "Commercial break",
    "description": "Gör en reklam paus för att sträcka på benen.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-267",
    "title": "Weather report 2",
    "description": "Rapportera temperaturen i kylskåpet (om du vågar kolla).",
    "type": "subjective",
    "timeLimitSeconds": 90,
    "submissionMode": "physical"
  },
  {
    "id": "c-268",
    "title": "Tre saker",
    "description": "Presentera tre saker du alltid har med dig (påhittat halvt räknas).",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-269",
    "title": "Show and tell",
    "description": "Visa upp det mest pinsamma i din telefon (inga privata bilder!).",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-270",
    "title": "Talent",
    "description": "Visa en dold talang.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-271",
    "title": "No talent",
    "description": "Visa upp något du är dålig på med stolthet.",
    "type": "subjective",
    "timeLimitSeconds": 90,
    "submissionMode": "physical"
  },
  {
    "id": "c-272",
    "title": "Group pose",
    "description": "Organisera gruppen i en pose. Testledaren fotar eller bedömer.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-273",
    "title": "Human letter",
    "description": "Bilda en bokstav med kroppen tillsammans med andra — eller solo.",
    "type": "subjective",
    "timeLimitSeconds": 90,
    "submissionMode": "physical"
  },
  {
    "id": "c-274",
    "title": "Soundtrack",
    "description": "Nynna en låt som passar testledaren just nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-275",
    "title": "Sound effect",
    "description": "Gör ljudeffekter till testledarens promenad.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-276",
    "title": "Slow clap",
    "description": "Starta en slow clap som känns motiverad.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-277",
    "title": "Standing ovation",
    "description": "Ge testledaren stående ovation. Mest genuint vinner.",
    "type": "subjective",
    "timeLimitSeconds": 90,
    "submissionMode": "physical"
  },
  {
    "id": "c-278",
    "title": "Award speech",
    "description": "Håll ett tacktal för en prisutdelning som inte hänt.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-279",
    "title": "Acceptance speech",
    "description": "Tacka någon som inte finns.",
    "type": "subjective",
    "timeLimitSeconds": 90,
    "submissionMode": "physical"
  },
  {
    "id": "c-280",
    "title": "Translator",
    "description": "Översätt testledarens senaste mening till \"piratsvenska\".",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-281",
    "title": "Lawyer",
    "description": "Försvara varför du borde få poäng utan att göra något.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-282",
    "title": "Detective",
    "description": "Lös vem som tog sista kakan (påhittat brott).",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-283",
    "title": "Scientist",
    "description": "Förklara en vardaglig sak med fel vetenskap.",
    "type": "subjective",
    "timeLimitSeconds": 90,
    "submissionMode": "physical"
  },
  {
    "id": "c-284",
    "title": "Historian",
    "description": "Förklara ursprunget till en soffa som om den vore antik.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-285",
    "title": "Coach",
    "description": "Ge testledaren en halvtidspeptalk.",
    "type": "subjective",
    "timeLimitSeconds": 90,
    "submissionMode": "physical"
  },
  {
    "id": "c-286",
    "title": "Pappersplan 2",
    "description": "Vik det mest aerodynamiska föremålet av papper du kan. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-287",
    "title": "Mumie",
    "description": "Linda in dig själv (eller en kudde) som en mumie snabbast. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-288",
    "title": "Tidning hatt",
    "description": "Gör en hatt av tidning eller papper och bär den med stolthet. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-289",
    "title": "Känslo-emoji",
    "description": "Få testledaren att gissa vilken emoji du spelar. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 90,
    "submissionMode": "physical"
  },
  {
    "id": "c-290",
    "title": "TV-kanal",
    "description": "Byt \"kanal\" genom att spela upp tre olika genrer på 10 sek vardera. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-291",
    "title": "Reality intro",
    "description": "Gör en reality-intro av dig själv med namn och catchphrase. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 90,
    "submissionMode": "physical"
  },
  {
    "id": "c-292",
    "title": "Kattlåda",
    "description": "Bygg en låda som en katt skulle ogilla. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 150,
    "submissionMode": "physical"
  },
  {
    "id": "c-293",
    "title": "Hundpark",
    "description": "Låtsas vara en hund som precis kom till parken. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 90,
    "submissionMode": "physical"
  },
  {
    "id": "c-294",
    "title": "Golf",
    "description": "Spela minigolf med det du har. Färst i hål vinner. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-295",
    "title": "Bowling",
    "description": "Bowla med ett föremål mot PET-flaskor eller liknande. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-296",
    "title": "Dart",
    "description": "Kasta något mjukt mot en måltavla (ritad på papper). Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-297",
    "title": "Memory",
    "description": "Hämta exakt samma föremål som testledaren beskriver från minnet. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-298",
    "title": "Blind fetch",
    "description": "Hämta det testledaren säger medan du blundar. Din tid börjar nu.",
    "type": "speed",
    "timeLimitSeconds": 120,
    "submissionMode": "physical"
  },
  {
    "id": "c-299",
    "title": "Synonym",
    "description": "Hitta ett annat ord för \"test\" och förklara det som ett nytt koncept. Din tid börjar nu.",
    "type": "subjective",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  },
  {
    "id": "c-300",
    "title": "Haiku om mat",
    "description": "Skriv ett haiku om något ätbart i rummet. Din tid börjar nu.",
    "type": "creative",
    "timeLimitSeconds": 120,
    "submissionMode": "text"
  }
]
