import type { Challenge } from '../challengeTypes.js'

/** English challenge titles → Swedish. */
const titleSv: Record<string, string> = {
  'Breaking news': 'Extranyheter',
  'Drama queen': 'Dramaqueen',
  'Freeze dance': 'Dans och frys',
  Logo: 'Logotyp',
  'Fake tweet': 'Fejktweet',
  Obituary: 'Nekrolog',
  Manual: 'Bruksanvisning',
  Acronym: 'Förkortning',
  'News anchor': 'Nyhetsankare',
  'Nature documentary': 'Naturdokumentär',
  Sport: 'Sportkommentator',
  Weather: 'Väderrapport',
  Auction: 'Auktion',
  Motivation: 'Motivationstal',
  Therapist: 'Snabbterapi',
  'Fortune teller': 'Spåkvinna',
  Chef: 'Kocken',
  Pilot: 'Piloten',
  'Tour guide': 'Museiguide',
  Villain: 'Skurken',
  'Hero entrance': 'Hjälte-entrée',
  'Slow motion': 'Slowmotion',
  Mime: 'Mim',
  Puppet: 'Marionett',
  'Evil laugh': 'Skurkskratt',
  'Compliment battle': 'Komplimangslag',
  'Pickup line': 'Raggningsreplik',
  Roast: 'Mild roast',
  Breakup: 'Dramatiskt slut',
  'Squat hold': 'Squat-håll',
  Superman: 'Supermannen',
  'Te-glas': 'Tekopp',
  'Time capsule': 'Tidskapsel',
  'Red carpet': 'Röda mattan',
  'Push-ups snabb': 'Armhävningar snabbt',
  'Jumping jacks': 'Hoppjacks',
  'High knees': 'Knähöjningar',
  Spin: 'Snurr',
  Transfer: 'Flytt',
  Sort: 'Sortera',
  Fold: 'Vika',
  'Stack cups': 'Muggstapel',
  'Ping pong': 'Pingpong',
  'Keepy uppy': 'Håll i luften',
  'Crab walk': 'Krabbgång',
  'Bear crawl': 'Björngång',
  Backwards: 'Baklänges',
  'Whisper run': 'Tyst sprint',
  'Object relay': 'Stafett',
  'Paper tear': 'Pappersremsa',
  Knot: 'Knutar',
  'Coin flip': 'Myntkast',
  'Dice roll': 'Tärningskast',
  'Card house': 'Korthus',
  'Mystery box': 'Mysteriebox',
  'Outfit swap': 'Byt accessoar',
  'Sock puppet': 'Strumpdocka',
  'Commercial break': 'Reklampaus',
  'Weather report 2': 'Väderrapport 2',
  'Show and tell': 'Visa och berätta',
  'No talent': 'Ingen talang',
  'Group pose': 'Grupppos',
  'Human letter': 'Mänsklig bokstav',
  'Sound effect': 'Ljudeffekt',
  'Slow clap': 'Långsam applåd',
  'Standing ovation': 'Stående ovation',
  'Award speech': 'Pristacktal',
  'Acceptance speech': 'Tacktal',
  'Blind fetch': 'Blint uppdrag',
  'Left hand': 'Fel hand',
  'Weather report': 'Väderrapport',
  'Pillow fort': 'Kuddfästning',
  'Film pitch': 'Filmpitch',
  'Bucket list': 'Att-göra-lista',
  'Roast light': 'Mild roast',
  'High five': 'Highfive',
  'Fist bump': 'Knoge',
  'Walk of shame': 'Skam-vandring',
  'Victory lap': 'Segervarv',
  'Slow walk': 'Slowmotion-promenad',
  'Hide item': 'Göm föremål',
  'Find item': 'Hitta föremål',
  'Twin item': 'Tvillingföremål',
  'Worst gift': 'Sämsta presenten',
  'Best gift': 'Bästa presenten',
  'Reverse charades': 'Omvänd charader',
  'Sound quiz': 'Ljudquiz',
  'One word': 'Ett ord',
  'Two truths': 'Två sanningar',
  'Would you rather': 'Skulle du hellre',
  'Hot take': 'Het åsikt',
  'Unpopular opinion': 'Impopulär åsikt',
  'Complaint letter': 'Klagobrev',
  'Thank you note': 'Tackkort',
  'Fortune cookie': 'Lyckokaka',
  'Spell name': 'Trollformel',
  'Toe touch': 'Törörning',
  'Push ups': 'Armhävningar',
  'Sit ups': 'Situps',
  'Lunge walk': 'Utfallssteg',
  'Egg spoon': 'Skedbalans',
  'Book balance': 'Bokbalans',
  'No thumbs': 'Utan tummar',
  'Breath hold': 'Andningshåll',
  'Staring contest': 'Stirratävling',
  'No smile': 'Inget leende',
  'Compliment chain': 'Komplimangskedja',
  'Group photo': 'Gruppfoto',
  'Human pyramid': 'Mänsklig pyramid',
  'Red light': 'Rött ljus',
  'Musical chairs': 'Musikaliska stolar',
  'Hot potato': 'Het potatis',
  'Pass the sound': 'Skicka ljudet',
  'Build tower': 'Bygg torn',
  'Paper hat 2': 'Pappershatt 2',
  'Museum label': 'Museietikett',
  'Wanted poster': 'Efterlysning',
  'Instruction manual': 'Bruksanvisning',
  'Warning label': 'Varningsetikett',
  'Product review': 'Produktrecension',
  'Yelp review': 'Nätrecension',
  TripAdvisor: 'Reseguide-recension',
  'Final toast': 'Skåltal',
  'Rap intro': 'Rap-intro',
  'Reality intro': 'Reality-intro',
  'Reality-klipp': 'Reality-klipp',
  'TV-kanal': 'TV-kanal',
  'Bubble face': 'Bubbelkind',
  'Tongue out': 'Tunga ut',
  'Finger fight': 'Fingerduell',
  'Ingen ord': 'Ingen ord',
  'Tongue twister 2': 'Tungvrickare 2',
  'Plank 2': 'Plankan 2',
  'Wall sit 2': 'Vägg-sits 2',
  'Auction 2': 'Auktion 2',
  'Pappersplan 2': 'Pappersplan 2',
  'Limbo 2': 'Limbo 2',
  'Robot 2': 'Robot 2',
  'Staty 2': 'Staty 2',
  Translator: 'Översättare',
  Lawyer: 'Advokaten',
  Detective: 'Detektiven',
  Scientist: 'Forskaren',
  Historian: 'Historikern',
  Coach: 'Coachen',
  'Soundtrack': 'Soundtrack',
  'Beatbox': 'Beatbox',
  'Whistle': 'Vissling',
  'Humming': 'Nynnande',
  'Synchronized': 'Synkron',
  'Mirror': 'Spegel',
  'Shadow': 'Skugga',
  'Charades': 'Charader',
  'Collage': 'Collage',
  'Recipe': 'Recept',
  'Spell': 'Trollformel',
  'Bridge': 'Bro',
  'Origami': 'Origami',
  'Alien': 'Utomjording',
  'LinkedIn': 'LinkedIn-inlägg',
  'Tinder': 'Tinder-profil',
  'Yelp': 'Nätrecension',
  'Amazon': 'Amazon-recension',
  'Facebook': 'Fejkbok-status',
  'Status': 'Statusuppdatering',
  Podcast: 'Podcast',
  Whisper: 'Viska',
  Campfire: 'Lägereld',
  Talent: 'Talang',
  Memory: 'Minnesspel',
  Infomercial: 'Reklamfilm',
  'Mild roast': 'Lättroast',
  Shakespeare: 'Shakespeare',
  Golf: 'Golf',
  Bowling: 'Bowling',
  Dart: 'Dart',
  Beatbox: 'Beatbox',
  Zombie: 'Zombie',
  Ninja: 'Ninja',
  Viking: 'Viking',
  Cocktail: 'Cocktail',
  Origami: 'Origami',
  Limbo: 'Limbo',
  Museum: 'Museum',
  Mode: 'Mode',
  Zoo: 'Djurpark',
  Parad: 'Parad',
  Superman: 'Supermannen',
  Mim: 'Mim',
  Opera: 'Opera',
  Rap: 'Rap',
  Accent: 'Accent',
  Magiker: 'Magiker',
  Gissning: 'Gissning',
  Skvaller: 'Skvaller',
  Mantra: 'Mantra',
  Rim: 'Rim',
  Papegoja: 'Papegoja',
  Mumie: 'Mumie',
  Hundpark: 'Hundpark',
  Synonym: 'Synonym',
  Alibi: 'Alibi',
  Manifest: 'Manifest',
  Slogan: 'Slogan',
  Dialog: 'Dialog',
  Film: 'Film',
  Dröm: 'Dröm',
  Lista: 'Lista',
  Namn: 'Namn',
  Brev: 'Brev',
  Regler: 'Regler',
  Reklam: 'Reklam',
  Rubrik: 'Rubrik',
  Recension: 'Recension',
  Horoskop: 'Horoskop',
  Definition: 'Definition',
  Emblem: 'Emblem',
  Flagga: 'Flagga',
  Monster: 'Monster',
  Robot: 'Robot',
  Dinosaurie: 'Dinosaurie',
  Husdjur: 'Husdjur',
  Skor: 'Skor',
  Hatt: 'Hatt',
  Vinter: 'Vinter',
  Sommar: 'Sommar',
  Musik: 'Musik',
  Kaos: 'Kaos',
  Ord: 'Ord',
  Pil: 'Pil',
  Hand: 'Hand',
  Fot: 'Fot',
  Bil: 'Bil',
  Båt: 'Båt',
  Träd: 'Träd',
  Blomma: 'Blomma',
  Stad: 'Stad',
  Bro: 'Bro',
  Glass: 'Glass',
  Mat: 'Mat',
  Present: 'Present',
  Altare: 'Altare',
  Tron: 'Tron',
  Krona: 'Krona',
  Trofé: 'Trofé',
  Kast: 'Kast',
  Snurr: 'Snurr',
  Andning: 'Andning',
  Kedja: 'Kedja',
  Iskall: 'Iskall',
  Vänta: 'Vänta',
  Fort: 'Fort',
}

const descReplacements: [RegExp, string][] = [
  [/over-the-top/gi, 'sprakande'],
  [/slow motion/gi, 'slowmotion'],
  [/high five/gi, 'highfive'],
  [/fist bump/gi, 'knoge'],
  [/walk of shame/gi, 'skam-vandring'],
  [/Would you rather/gi, 'Skulle du hellre'],
  [/would you rather/gi, 'skulle du hellre'],
  [/fortune cookie/gi, 'lyckokaka'],
  [/jumping jacks/gi, 'hoppjacks'],
  [/push ups/gi, 'armhävningar'],
  [/push-ups/gi, 'armhävningar'],
  [/sit ups/gi, 'situps'],
  [/crab walk/gi, 'krabbgång'],
  [/bear crawl/gi, 'björngång'],
  [/keepy uppy/gi, 'håll i luften'],
  [/reverse charades/gi, 'omvänd charader'],
  [/bucket list/gi, 'att-göra-lista'],
  [/hot take/gi, 'het åsikt'],
  [/show and tell/gi, 'visa och berätta'],
  [/slow clap/gi, 'långsam applåd'],
  [/standing ovation/gi, 'stående ovation'],
  [/breaking news/gi, 'extranyheter'],
  [/Left hand/gi, 'Fel hand'],
  [/musical chairs/gi, 'musikaliska stolar'],
  [/hot potato/gi, 'het potatis'],
  [/red light/gi, 'rött ljus'],
  [/staring contest/gi, 'stirratävling'],
  [/thank you note/gi, 'tackkort'],
  [/complaint letter/gi, 'klagobrev'],
  [/unpopular opinion/gi, 'impopulär åsikt'],
  [/two truths/gi, 'två sanningar'],
  [/one word/gi, 'ett ord'],
  [/pickup line/gi, 'raggningsreplik'],
  [/compliment battle/gi, 'komplimangslag'],
  [/nature documentary/gi, 'naturdokumentär'],
  [/weather report/gi, 'väderrapport'],
  [/evil laugh/gi, 'skurkskratt'],
  [/hero entrance/gi, 'hjälte-entrée'],
  [/fortune teller/gi, 'spåkvinna'],
  [/tour guide/gi, 'museiguide'],
  [/news anchor/gi, 'nyhetsankare'],
  [/fake tweet/gi, 'fejktweet'],
  [/squat hold/gi, 'squat-håll'],
  [/mystery box/gi, 'mysteriebox'],
  [/sock puppet/gi, 'strumpdocka'],
  [/commercial break/gi, 'reklampaus'],
  [/group pose/gi, 'grupppos'],
  [/human letter/gi, 'mänsklig bokstav'],
  [/human pyramid/gi, 'mänsklig pyramid'],
  [/build tower/gi, 'bygg torn'],
  [/hide item/gi, 'göm föremål'],
  [/find item/gi, 'hitta föremål'],
  [/victory lap/gi, 'segervarv'],
  [/pillow fort/gi, 'kuddfästning'],
  [/film pitch/gi, 'filmpitch'],
  [/instruction manual/gi, 'bruksanvisning'],
  [/warning label/gi, 'varningsetikett'],
  [/wanted poster/gi, 'efterlysning'],
  [/product review/gi, 'produktrecension'],
  [/final toast/gi, 'skåltal'],
  [/catchphrase/gi, 'catchphrase'],
  [/clickbait/gi, 'klickbeten'],
  [/high knees/gi, 'knähöjningar'],
  [/catchphrase/gi, 'signaturreplik'],
  [/reality-intro/gi, 'realityintro'],
]

export function localizeChallengeSv(challenge: Challenge): Challenge {
  const title = titleSv[challenge.title] ?? challenge.title
  let description = challenge.description
  for (const [pattern, replacement] of descReplacements) {
    description = description.replace(pattern, replacement)
  }
  if (title === challenge.title && description === challenge.description) {
    return challenge
  }
  return { ...challenge, title, description }
}

export function localizeChallengesSv(challenges: Challenge[]): Challenge[] {
  return challenges.map(localizeChallengeSv)
}
